use axum::{Router, routing::post};

use crate::app::AppState;

use super::controller;

pub fn router() -> Router<AppState> {
    Router::new()
        .route(
            "/protocol-admin/initialize-protocol",
            post(controller::initialize_protocol),
        )
        .route(
            "/protocol-admin/initialize-protocol/simulate",
            post(controller::simulate_initialize_protocol),
        )
        .route(
            "/protocol-admin/pause-protocol",
            post(controller::pause_protocol),
        )
        .route(
            "/protocol-admin/pause-protocol/simulate",
            post(controller::simulate_pause_protocol),
        )
        .route(
            "/protocol-admin/set-protocol-config",
            post(controller::set_protocol_config),
        )
        .route(
            "/protocol-admin/set-protocol-config/simulate",
            post(controller::simulate_set_protocol_config),
        )
        .route(
            "/protocol-admin/register-protocol-vaults",
            post(controller::register_protocol_vaults),
        )
        .route(
            "/protocol-admin/register-protocol-vaults/simulate",
            post(controller::simulate_register_protocol_vaults),
        )
        .route(
            "/protocol-admin/set-protocol-authorities",
            post(controller::set_protocol_authorities),
        )
        .route(
            "/protocol-admin/set-protocol-authorities/simulate",
            post(controller::simulate_set_protocol_authorities),
        )
        .route(
            "/protocol-admin/set-multisig-config",
            post(controller::set_multisig_config),
        )
        .route(
            "/protocol-admin/set-multisig-config/simulate",
            post(controller::simulate_set_multisig_config),
        )
        .route(
            "/protocol-admin/set-timelock-delay",
            post(controller::set_timelock_delay),
        )
        .route(
            "/protocol-admin/set-timelock-delay/simulate",
            post(controller::simulate_set_timelock_delay),
        )
        .route(
            "/protocol-admin/queue-protocol-config-change",
            post(controller::queue_protocol_config_change),
        )
        .route(
            "/protocol-admin/queue-protocol-config-change/simulate",
            post(controller::simulate_queue_protocol_config_change),
        )
        .route(
            "/protocol-admin/execute-protocol-config-change",
            post(controller::execute_protocol_config_change),
        )
        .route(
            "/protocol-admin/execute-protocol-config-change/simulate",
            post(controller::simulate_execute_protocol_config_change),
        )
        .route(
            "/protocol-admin/begin-upgrade-authority-handoff",
            post(controller::begin_upgrade_authority_handoff),
        )
        .route(
            "/protocol-admin/begin-upgrade-authority-handoff/simulate",
            post(controller::simulate_begin_upgrade_authority_handoff),
        )
        .route(
            "/protocol-admin/accept-upgrade-authority-handoff",
            post(controller::accept_upgrade_authority_handoff),
        )
        .route(
            "/protocol-admin/accept-upgrade-authority-handoff/simulate",
            post(controller::simulate_accept_upgrade_authority_handoff),
        )
        .route(
            "/protocol-admin/emergency-rotate-admin",
            post(controller::emergency_rotate_admin),
        )
        .route(
            "/protocol-admin/emergency-rotate-admin/simulate",
            post(controller::simulate_emergency_rotate_admin),
        )
        .route(
            "/protocol-admin/set-global-loyalty-multiplier",
            post(controller::set_global_loyalty_multiplier),
        )
        .route(
            "/protocol-admin/set-global-loyalty-multiplier/simulate",
            post(controller::simulate_set_global_loyalty_multiplier),
        )
        .route("/protocol-admin/grant-role", post(controller::grant_role))
        .route(
            "/protocol-admin/grant-role/simulate",
            post(controller::simulate_grant_role),
        )
        .route("/protocol-admin/revoke-role", post(controller::revoke_role))
        .route(
            "/protocol-admin/revoke-role/simulate",
            post(controller::simulate_revoke_role),
        )
        .route(
            "/protocol-admin/rotate-authority",
            post(controller::rotate_authority),
        )
        .route(
            "/protocol-admin/rotate-authority/simulate",
            post(controller::simulate_rotate_authority),
        )
        .route(
            "/protocol-admin/initialize-vault",
            post(controller::initialize_vault),
        )
        .route(
            "/protocol-admin/initialize-vault/simulate",
            post(controller::simulate_initialize_vault),
        )
        .route(
            "/protocol-admin/snapshot-vault",
            post(controller::snapshot_vault),
        )
        .route(
            "/protocol-admin/snapshot-vault/simulate",
            post(controller::simulate_snapshot_vault),
        )
        .route(
            "/protocol-admin/withdraw-vault",
            post(controller::withdraw_vault),
        )
        .route(
            "/protocol-admin/withdraw-vault/simulate",
            post(controller::simulate_withdraw_vault),
        )
        .route(
            "/protocol-admin/upsert-registry-entry",
            post(controller::upsert_registry_entry),
        )
        .route(
            "/protocol-admin/upsert-registry-entry/simulate",
            post(controller::simulate_upsert_registry_entry),
        )
}
